version: "3.7"

services:

  malt_scraper:
    build: ./app
    container_name: malt_scraper
    shm_size: '2gb'
    restart: unless-stopped
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - MONGO_URI=mongodb://root:example@mongo:27017/
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-ui:
    image: mongo-express
    ports:
      - 8081:8081
    restart: 
      unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/